export const API_ENDPOINTS = {
  health: '/api/health',
  auth: {
    login: '/api/auth/login',
    register: '/api/auth/register',
    me: '/api/auth/me',
    updateProfile: '/api/auth/me/profile',
    logout: '/api/auth/logout',
    resetPassword: '/api/auth/reset-password',
  },
  systemAdmin: {
    dashboardStats: '/api/system-admin/dashboard/stats',
    dashboardActivity: '/api/system-admin/dashboard/activity',
    topSocieties: '/api/system-admin/dashboard/top-societies',
    buildings: '/api/system-admin/buildings',
    settingsMe: '/api/system-admin/settings/me',
    admins: '/api/system-admin/admins',
    inviteAdmin: '/api/system-admin/admins/invite',
      deleteAdmin: (adminId: string) => `/api/system-admin/admins/${adminId}`,
  },
  admin: {
    dashboardStats: '/api/admin/dashboard/stats',
    units: '/api/admin/units',
    residents: '/api/admin/residents',
    inviteResident: '/api/admin/residents/invite',
    security: '/api/admin/security',
    securityStats: '/api/admin/security/stats',
    inviteSecurity: '/api/admin/security/invite',
    announcements: '/api/admin/announcements',
    deleteAnnouncement: (id: string) => `/api/admin/announcements/${id}`,
    maintenance: '/api/admin/maintenance',
    maintenanceStart: (id: string) => `/api/admin/maintenance/${id}/start`,
    maintenanceResolve: (id: string) => `/api/admin/maintenance/${id}/resolve`,
    maintenanceCancel: (id: string) => `/api/admin/maintenance/${id}/cancel`,
    events: '/api/admin/events',
    deleteEvent: (id: string) => `/api/admin/events/${id}`,
    payments: '/api/admin/payments',
    triggerOverdueCheck: '/api/admin/payments/trigger-overdue-check',
    adminDetail: (id: string) => `/api/admin/residents/detail/${id}`,
    paymentsBulk: '/api/admin/payments/bulk',
    paymentsIndividual: '/api/admin/payments/individual',
    paymentsMarkPaid: (id: string) => `/api/admin/payments/${id}/mark-paid`,
    paymentsWaive: (id: string) => `/api/admin/payments/${id}/waive`,
  },
  resident: {
    profile: '/api/resident/profile',
    residentProfileUpdate: '/api/resident/profile',
    dashboardStats: '/api/resident/dashboard-stats',
    announcements: '/api/resident/announcements',
    maintenance: '/api/resident/maintenance',
    maintenanceCancel: (id: string) => `/api/resident/maintenance/${id}/cancel`,
    visitors: '/api/resident/visitors',
    payments: '/api/resident/payments',
    events: '/api/resident/events',
    forumPosts: '/api/resident/forum-posts',
  },
  security: {
    dashboardStats: '/api/security/dashboard-stats',
    announcements: '/api/security/announcements',
    visitors: '/api/security/visitors',
    visitorApprove: (id: string) => `/api/security/visitors/${id}/approve`,
    visitorDeny: (id: string) => `/api/security/visitors/${id}/deny`,
    visitorCheckin: (id: string) => `/api/security/visitors/${id}/checkin`,
    visitorCheckout: (id: string) => `/api/security/visitors/${id}/checkout`,
    incidents: '/api/security/incidents',
    updateIncident: (id: string) => `/api/security/incidents/${id}`,
    accessPoints: '/api/security/access-points',
    accessLogs: '/api/security/access-logs',
    toggleAccessPoint: (id: string) => `/api/security/access-points/${id}/toggle`,
    patrolRounds: '/api/security/patrol-rounds',
    patrolRoutes: '/api/security/patrol-routes',
    completePatrolRound: (roundId: string) => `/api/security/patrol-rounds/${roundId}/complete`,
    checkCheckpoint: (roundId: string, checkpointId: number) => `/api/security/patrol-rounds/${roundId}/checkpoints/${checkpointId}`,
    logs: '/api/security/logs',
    reports: '/api/security/reports',
    downloadReport: (reportId: string) => `/api/security/reports/${reportId}/download`,
  },
};
