export const API_ENDPOINTS = {
  health: '/api/health',
  auth: {
    login: '/api/auth/login',
    register: '/api/auth/register',
    me: '/api/auth/me',
    updateProfile: '/api/auth/me/profile',
    logout: '/api/auth/logout',
    resetPassword: '/api/auth/reset-password',
  },
  systemAdmin: {
    dashboardStats: '/api/system-admin/dashboard/stats',
    dashboardActivity: '/api/system-admin/dashboard/activity',
    topSocieties: '/api/system-admin/dashboard/top-societies',
    buildings: '/api/system-admin/buildings',
    settingsMe: '/api/system-admin/settings/me',
    admins: '/api/system-admin/admins',
    inviteAdmin: '/api/system-admin/admins/invite',
      deleteAdmin: (adminId: string) => `/api/system-admin/admins/${adminId}`,
  },
  admin: {
    dashboardStats: '/api/admin/dashboard/stats',
    units: '/api/admin/units',
    residents: '/api/admin/residents',
    inviteResident: '/api/admin/residents/invite',
    security: '/api/admin/security',
    inviteSecurity: '/api/admin/security/invite',
    announcements: '/api/admin/announcements',
    deleteAnnouncement: (id: string) => `/api/admin/announcements/${id}`,
    events: '/api/admin/events',
    deleteEvent: (id: string) => `/api/admin/events/${id}`,
  },
  resident: {
    profile: '/api/resident/profile',
    dashboardStats: '/api/resident/dashboard-stats',
    announcements: '/api/resident/announcements',
    maintenance: '/api/resident/maintenance',
    visitors: '/api/resident/visitors',
    payments: '/api/resident/payments',
    events: '/api/resident/events',
    forumPosts: '/api/resident/forum-posts',
  },
  security: {
    announcements: '/api/security/announcements',
  },
};
